### ISSUE TITLE
Explanation of c and delta for sampler

### ISSUE THREAD

**Issue by fionafibration** [anrosent/LT-code#6]
Any chance of an explanation for the C and delta for the sampler? I'm getting nearly 20% overhead from the LT coding with the defaults

**Comment by anrosent** [comment]
I forget exactly why I set these parameters, this was originally for a school project so it might have been provided in the spec. Looking at the [reference linked in the README](http://www.inference.org.uk/itprnn/book.pdf), this parameterization appears among the histograms on page 593. I suppose it's not a clear winner, with higher mean packet requirement for recovery but lower variance than the rest. 

If the overhead you're talking about is time spent in the sampling functions, seems probably higher than it could be, but then again the encoder isn't doing much else besides that and the XORs.

Hope this helps

**Comment by fionafibration** [comment]
The overhead is in the number of blocks taken to decode. I suppose it may mean more redundant decoding, but if you have any idea of how I can set it to be less redundant and have a lower K', I'd appreciate it. Thanks!

**Comment by anrosent** [comment]
Sorry for the delay on this, responding in case the question remains.

While you could set the degree distribution to be $$P(1) = 1$$, thus preventing the encoder from transmitting redundant blocks, I'm not sure if this can be achieved simply by tuning $$\delta$$ and $$\tau$$ in the sampler provided. Further, completely eliminating sampling overhead would also mean replacing the block sampler, since even if you always select with degree 1 it is unlikely that the block sampler would select $K$ unique blocks in a row. 

I think that the tradeoff here is that the sampling is what provides the robustness to packet loss, and if packet loss isn't an issue then you could probably do better with a different algorithm. Hope this helps!
